import { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from "@/lib/types.ts";

interface LanguageContextType {
  language: Language;
  languages: Language[];
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const globals = {
  app_name: "Chatlog",
  rtech: "RTech",
  instagram_url: "https://www.instagram.com/rtech_solution",
  linkedin_url: "https://www.linkedin.com/company/r-techsolution",
  portugues_brasil: "Portuguese (Brazil)",
  ingles: "English"
}

const translations = {
  pt: {
    // Header
    inicio: "Início",
    recursos: "Recursos", 
    beneficios: "Benefícios",
    precos: "Preços",
    faq: "FAQ",
    teste_gratis: "Teste grátis por 3 dias",

    // Hero
    revolucione_atendimento: "Revolucione seu atendimento com IA",
    automatize_conversas: "Automatize conversas, aumente vendas e ofereça suporte 24/7 com nosso",
    chatbot_inteligente: "chatbot inteligente",
    otimize_comunicacao: "Otimize a comunicação com seus clientes utilizando chatbots personalizados e atendimento humano integrado, tudo em um único número de WhatsApp.",
    testar_gratis: "Testar Grátis",
    saiba_mais: "Saiba mais",
    sempre_disponivel: "Sempre disponível",
    ia_inteligente: "IA Inteligente",
    respostas_precisas: "Respostas precisas",
    seguro: "Seguro",
    dados_protegidos: "Dados protegidos",
    online_24_7: "24/7 Online",
    chat_ola: "Olá! Como posso ajudá-lo hoje?",
    chat_preciso: "Preciso de informações sobre seus produtos",
    chat_claro: "Claro! Aqui estão nossos principais produtos...",
    digite_mensagem: "Digite sua mensagem...",

    // Features
    recursos_poderosos: "Recursos Poderosos",
    tecnologia_de_ponta: "Tecnologia de Ponta",
    para_seu_negocio: "para seu Negócio",
    descubra_como: "Descubra como nossa plataforma pode transformar seu atendimento ao cliente com recursos inovadores e inteligência artificial de última geração.",
    atendimento_natural: "Atendimento Natural",
    atendimento_natural_desc: "Interações que simulam conversas humanas, aumentando o engajamento.",
    automacao_tarefas: "Automação de Tarefas",
    automacao_tarefas_desc: "Respostas automáticas para perguntas frequentes, liberando sua equipe para tarefas mais complexas.",
    integracao_multicanal: "Integração Multicanal",
    integracao_multicanal_desc: "Atuação em diversos canais como WhatsApp, Instagram e seu site.",
    disponibilidade_24_7: "Disponibilidade 24/7",
    disponibilidade_24_7_desc: "Seus clientes atendidos a qualquer hora, sem interrupções.",
    reducao_tempo: "De redução no tempo de resposta",
    aumento_satisfacao: "De aumento na satisfação do cliente ",
    economia_custos: "De economia nos custos operacionais",
    suporte_disponivel: "Sem pausa, sem férias, sem erros",
    empresas_atendidas: "Empresas Atendidas",
    ia_avancada: "IA Avançada",
    ia_avancada_desc: "Processamento de linguagem natural para conversas mais humanas",
    integracao_facil: "Integração Fácil",
    integracao_facil_desc: "Conecte com WhatsApp, Telegram, site e redes sociais",
    analytics: "Analytics",
    analytics_desc: "Relatórios detalhados sobre performance e satisfação",

    // Agent Models
    solucoes_prontas: "Soluções Prontas",
    modelos_de: "Modelos de",
    agentes_prontos: "Agentes Prontos",
    comece_rapidamente: "Comece rapidamente com nossos modelos pré-configurados para diferentes necessidades de negócio.",
    atendimento_cliente: "Atendimento ao Cliente",
    atendimento_cliente_desc: "Responde dúvidas, fornece informações e soluciona problemas comuns.",
    vendas: "Vendas",
    vendas_desc: "Qualifica leads, apresenta produtos e conduz o cliente até a finalização da compra.",
    agendamento: "Agendamento",
    agendamento_desc: "Marca reuniões, envia lembretes e gerência calendários.",
    suporte_tecnico: "Suporte Técnico",
    suporte_tecnico_desc: "Auxilia na resolução de questões técnicas e orienta o usuário.",

    // Benefits
    beneficios_titulo: "Por que escolher nosso ChatBot?",
    reducao_custos: "Redução de Custos",
    reducao_custos_desc: "Diminua até 70% dos custos operacionais",
    disponibilidade: "Disponibilidade 24/7",
    disponibilidade_desc: "Atendimento ininterrupto para seus clientes",
    aumento_vendas: "Aumento de Vendas",
    aumento_vendas_desc: "Converta mais leads em clientes",
    resultados_comprovados: "Resultados Comprovados",
    transforme_negocio: "Transforme seu Negócio com",
    resultados_mensuraveis: "Resultados Mensuráveis",
    veja_como_empresas: "Veja como empresas como a sua estão revolucionando o atendimento e aumentando seus resultados.",
    aumento_300_vendas: "Aumento de 300% nas Vendas",
    aumento_300_vendas_desc: "Nossos clientes relatam crescimento significativo nas conversões após implementar o chatbot.",
    satisfacao_cliente: "Satisfação do Cliente 95%+",
    satisfacao_cliente_desc: "Atendimento rápido e eficiente resulta em clientes mais satisfeitos e fiéis.",
    economia_tempo: "Economia de 80% no Tempo",
    economia_tempo_desc: "Automatize tarefas repetitivas e foque no que realmente importa para seu negócio.",
    reducao_60_custos: "Redução de 60% nos Custos",
    reducao_60_custos_desc: "Diminua gastos com atendimento manual mantendo a qualidade do serviço.",
    leads_qualificados: "Leads Qualificados 24/7",
    leads_qualificados_desc: "Capture e qualifique leads automaticamente, mesmo quando você não está online.",
    implementacao_24h: "Implementação em 24h",
    implementacao_24h_desc: "Configure seu chatbot em menos de um dia e comece a ver resultados imediatamente.",
    mercado_abrangente: "Mercado Abrangente",
    solucao_completa: "Uma solução completa para empresas que querem atender melhor e aumentar suas vendas. Atendemos uma vasta gama de setores e não temos limites para melhorar o seu negócio.",
    para_quem_chatlog: "Para quem é o",
    empresa_otimizar: "Empresas que desejam otimizar o atendimento ao cliente",
    ecommerce_automatizar: "E-commerces que buscam automatizar respostas frequentes",
    startup_escalar: "Startups que precisam escalar o suporte sem aumentar a equipe",
    agencias_solucoes: "Agências que oferecem soluções de atendimento automatizado para clientes",
    clinicas_volume: "Clínicas com grande volume de clientes",

    // Pricing
    escolha_plano: "Escolha seu Plano",
    planos_flexiveis: "Planos Flexíveis",
    ideal_para_negocio: "Ideal para seu Negócio",
    sem_contratos: "Sem contratos longos, sem taxas ocultas. Comece grátis e escale conforme cresce.",
    starter: "Starter",
    business: "Business",
    empresarial: "Empresarial",
    enterprise: "Enterprise",
    pequenos_negocios: "Perfeito para pequenos negócios",
    empresas_crescimento: "Ideal para empresas em crescimento",
    grandes_empresas: "Para grandes empresas",
    mais_popular: "Mais Popular",
    comecar_agora: "Começar Agora",
    escolher_plano: "Escolher Plano",
    por_mes: "/mês",
    implementacao: "implementação",
    mensagens_mes: "mensagens/mês",
    atendentes: "atendentes",
    chatbot_ilimitado: "Chatbot ilimitado",
    atendimento_setor: "Atendimento por setor",
    atendentes_simultaneos: "Atendentes simultâneos",
    robo_24: "Robô 24h por dia",
    visualizacao_tempo_real: "Visualização em tempo real da equipe",
    atendimento_humanizado: "Atendimento humanizado 24/7 com I.A",
    suporte_prioritario: "Suporte prioritário",
    suporte_prioritario_24: "Suporte prioritário 24/7",
    gestor_conta: "Gestor de conta disponível",
    integracao_crm: "Integração com CRM",
    treinamento_apoio: "Treinamento e apoio",
    consultoria_estrategica: "Consultoria estratégica",

    // FAQ
    perguntas_frequentes: "Perguntas Frequentes",
    respostas_para_suas: "Respostas para suas",
    duvidas: "Dúvidas",
    encontre_respostas: "Encontre respostas para as principais dúvidas sobre nossa plataforma de chatbot.",
    ainda_duvidas: "Ainda tem dúvidas?",
    equipe_especialistas: "Nossa equipe de especialistas está pronta para ajudar você a escolher a melhor solução para seu negócio.",
    falar_especialista: "Falar com Especialista",
    agendar_demonstracao: "Agendar Demonstração",

    // FAQ Questions
    faq_implementacao_q: "Como funciona a implementação do chatbot?",
    faq_implementacao_a: "A implementação é muito simples! Após a contratação, nossa equipe técnica configura seu chatbot em até 24 horas. Você receberá um treinamento completo e suporte durante todo o processo de setup.",
    faq_integracao_q: "Posso integrar com WhatsApp Business e outras plataformas?",
    faq_integracao_a: "Sim! Nosso chatbot se integra nativamente com WhatsApp Business, Instagram, Facebook Messenger, Telegram e pode ser incorporado ao seu site. Tudo gerenciado em uma única plataforma.",
    faq_perguntas_complexas_q: "O chatbot consegue entender perguntas complexas?",
    faq_perguntas_complexas_a: "Absolutamente! Nossa IA é treinada com processamento de linguagem natural avançado, conseguindo entender contexto, intenções e até mesmo gírias. A cada interação, o sistema fica mais inteligente.",
    faq_nao_sabe_responder_q: "E se o chatbot não souber responder alguma pergunta?",
    faq_nao_sabe_responder_a: "Quando o chatbot não consegue resolver uma questão, ele transfere automaticamente para um atendente humano, garantindo que nenhum cliente fique sem resposta. Você também pode configurar horários específicos para essa transferência.",
    faq_personalizar_q: "Posso personalizar as respostas do chatbot?",
    faq_personalizar_a: "Sim! Você tem controle total sobre as respostas. Pode criar fluxos personalizados, definir o tom de voz da marca, configurar respostas específicas para diferentes situações e até mesmo treinar o bot com informações do seu negócio.",
    faq_cobranca_q: "Como funciona a cobrança? Há contratos longos?",
    faq_cobranca_a: "Trabalhamos apenas com planos mensais, sem fidelidade. Você pode cancelar a qualquer momento. A cobrança é feita por número de mensagens processadas, garantindo que você pague apenas pelo que usar.",
    faq_seguranca_q: "O sistema é seguro? Como são tratados os dados dos clientes?",
    faq_seguranca_a: "Sim, a segurança é nossa prioridade. Todos os dados são criptografados e armazenados em servidores seguros. Estamos em conformidade com a LGPD e outras regulamentações de proteção de dados.",
    faq_conhecimento_tecnico_q: "Preciso ter conhecimento técnico para usar a plataforma?",
    faq_conhecimento_tecnico_a: "Não! Nossa plataforma foi desenvolvida para ser intuitiva e fácil de usar. Oferecemos treinamento completo e nossa equipe de suporte está sempre disponível para ajudar com qualquer dúvida.",
    faq_aumentar_vendas_q: "Como o chatbot pode aumentar minhas vendas?",
    faq_aumentar_vendas_a: "O chatbot qualifica leads 24/7, responde dúvidas instantaneamente, guia clientes pelo processo de compra, oferece produtos relacionados e nunca deixa um cliente sem atendimento, resultando em mais conversões e vendas.",

    // Footer
    sobre_nos: "Sobre Nós",
    recursos_footer: "Recursos",
    suporte: "Suporte",
    todos_direitos: "Todos os direitos reservados.",
    revolucione_atendimento_footer: "Revolucione seu atendimento com nossa plataforma de chatbot inteligente. Automatização, eficiência e experiência do cliente em um só lugar.",
    produto: "Produto",
    empresa: "Empresa",
    legal: "Legal",
    sobre: "Sobre",
    blog: "Blog",
    carreiras: "Carreiras",
    imprensa: "Imprensa",
    central_ajuda: "Central de Ajuda",
    documentacao: "Documentação",
    status: "Status",
    contato: "Contato",
    privacidade: "Privacidade",
    termos: "Termos",
    lgpd: "LGPD",
    cookies: "Cookies",
    fique_novidades: "Fique por dentro das novidades",
    receba_dicas: "Receba dicas, atualizações e cases de sucesso diretamente no seu email.",
    seu_email: "Seu melhor email",
    inscrever: "Inscrever",
    inscricao_sucesso: "Inscrição realizada com sucesso !",
    inscricao_erro: "Erro ao inscrever",
  },
  en: {
    // Header
    inicio: "Home",
    recursos: "Features",
    beneficios: "Benefits", 
    precos: "Pricing",
    faq: "FAQ",
    teste_gratis: "Free trial for 3 days",

    // Hero
    revolucione_atendimento: "Revolutionize your customer service with AI",
    automatize_conversas: "Automate conversations, increase sales and offer 24/7 support with our",
    chatbot_inteligente: "intelligent chatbot",
    otimize_comunicacao: "Optimize communication with your customers using personalized chatbots and integrated human service, all on a single WhatsApp number.",
    testar_gratis: "Try Free",
    saiba_mais: "Learn more",
    sempre_disponivel: "Always available",
    ia_inteligente: "Intelligent AI",
    respostas_precisas: "Accurate responses",
    seguro: "Secure",
    dados_protegidos: "Protected data",
    online_24_7: "24/7 Online",
    chat_ola: "Hello! How can I help you today?",
    chat_preciso: "I need information about your products",
    chat_claro: "Sure! Here are our main products...",
    digite_mensagem: "Type your message...",

    // Features
    recursos_poderosos: "Powerful Features",
    tecnologia_de_ponta: "Cutting-Edge Technology",
    para_seu_negocio: "for your Business",
    descubra_como: "Discover how our platform can transform your customer service with innovative features and state-of-the-art artificial intelligence.",
    atendimento_natural: "Natural Service",
    atendimento_natural_desc: "Interactions that simulate human conversations, increasing engagement.",
    automacao_tarefas: "Task Automation",
    automacao_tarefas_desc: "Automatic responses to frequent questions, freeing your team for more complex tasks.",
    integracao_multicanal: "Multichannel Integration",
    integracao_multicanal_desc: "Operation across various channels such as WhatsApp, Instagram, and your website.",
    disponibilidade_24_7: "24/7 Availability",
    disponibilidade_24_7_desc: "Your customers served at any time, without interruptions.",
    reducao_tempo: "Response time reduction",
    aumento_satisfacao: "Client satisfaction increase",
    economia_custos: "Operational cost reduction",
    suporte_disponivel: "No pauses, no vacations, no errors",
    empresas_atendidas: "Companies Served",
    ia_avancada: "Advanced AI",
    ia_avancada_desc: "Natural language processing for more human conversations",
    integracao_facil: "Easy Integration",
    integracao_facil_desc: "Connect with WhatsApp, Telegram, website and social media",
    analytics: "Analytics",
    analytics_desc: "Detailed reports on performance and satisfaction",

    // Agent Models
    solucoes_prontas: "Ready Solutions",
    modelos_de: "Models of",
    agentes_prontos: "Ready Agents",
    comece_rapidamente: "Get started quickly with our pre-configured models for different business needs.",
    atendimento_cliente: "Customer Service",
    atendimento_cliente_desc: "Answers questions, provides information and solves common problems.",
    vendas: "Sales",
    vendas_desc: "Qualifies leads, presents products and guides the customer to purchase completion.",
    agendamento: "Scheduling",
    agendamento_desc: "Schedules meetings, sends reminders and manages calendars.",
    suporte_tecnico: "Technical Support",
    suporte_tecnico_desc: "Assists in resolving technical issues and guides the user.",

    // Benefits
    beneficios_titulo: "Why choose our ChatBot?",
    reducao_custos: "Cost Reduction",
    reducao_custos_desc: "Reduce up to 70% of operational costs",
    disponibilidade: "24/7 Availability",
    disponibilidade_desc: "Uninterrupted service for your customers",
    aumento_vendas: "Sales Increase",
    aumento_vendas_desc: "Convert more leads into customers",
    resultados_comprovados: "Proven Results",
    transforme_negocio: "Transform your Business with",
    resultados_mensuraveis: "Measurable Results",
    veja_como_empresas: "See how companies like yours are revolutionizing customer service and increasing their results.",
    aumento_300_vendas: "300% Increase in Sales",
    aumento_300_vendas_desc: "Our customers report significant growth in conversions after implementing the chatbot.",
    satisfacao_cliente: "95%+ Customer Satisfaction",
    satisfacao_cliente_desc: "Fast and efficient service results in more satisfied and loyal customers.",
    economia_tempo: "80% Time Savings",
    economia_tempo_desc: "Automate repetitive tasks and focus on what really matters for your business.",
    reducao_60_custos: "60% Cost Reduction",
    reducao_60_custos_desc: "Reduce expenses with manual service while maintaining service quality.",
    leads_qualificados: "Qualified Leads 24/7",
    leads_qualificados_desc: "Capture and qualify leads automatically, even when you're not online.",
    implementacao_24h: "Implementation in 24h",
    implementacao_24h_desc: "Set up your chatbot in less than a day and start seeing results immediately.",
    mercado_abrangente: "Comprehensive market",
    solucao_completa: "A complete solution for companies that want to better serve and increase their sales. We serve a wide range of business and have no limits to improve your business.",
    para_quem_chatlog: "Who is",
    for: " for",
    empresa_otimizar: "Companies that want to optimize customer service",
    ecommerce_automatizar: "E-commerce businesses looking to automate frequent responses",
    startup_escalar: "Startups that need to scale support without increasing staff",
    agencias_solucoes: "Agencies offering automated service solutions to clients",
    clinicas_volume: "Clinics with high volume of clients",

    // Pricing
    escolha_plano: "Choose your Plan",
    planos_flexiveis: "Flexible Plans",
    ideal_para_negocio: "Perfect for your Business",
    sem_contratos: "No long contracts, no hidden fees. Start free and scale as you grow.",
    starter: "Starter",
    business: "Business",
    empresarial: "Corporate",
    enterprise: "Enterprise",
    pequenos_negocios: "Perfect for small businesses",
    empresas_crescimento: "Ideal for growing companies",
    grandes_empresas: "For large enterprises",
    mais_popular: "Most Popular",
    comecar_agora: "Get Started Now",
    escolher_plano: "Choose Plan",
    por_mes: "/month",
    implementacao: "implementation",
    mensagens_mes: "messages/month",

    // FAQ
    perguntas_frequentes: "Frequently Asked Questions",
    respostas_para_suas: "Get your",
    duvidas: "Questions Answered",
    encontre_respostas: "Find answers to the main questions about our chatbot platform.",
    ainda_duvidas: "Still have questions?",
    equipe_especialistas: "Our team of experts is ready to help you choose the best solution for your business.",
    falar_especialista: "Talk to an Expert",
    agendar_demonstracao: "Schedule a Demo",

    // FAQ Questions
    faq_implementacao_q: "How does chatbot implementation work?",
    faq_implementacao_a: "Implementation is very simple! After signing up, our technical team configures your chatbot within 24 hours. You'll receive complete training and support throughout the setup process.",
    faq_integracao_q: "Can I integrate with WhatsApp Business and other platforms?",
    faq_integracao_a: "Yes! Our chatbot integrates natively with WhatsApp Business, Instagram, Facebook Messenger, Telegram and can be embedded on your website. All managed in a single platform.",
    faq_perguntas_complexas_q: "Can the chatbot understand complex questions?",
    faq_perguntas_complexas_a: "Absolutely! Our AI is trained with advanced natural language processing, able to understand context, intentions and even slang. With each interaction, the system gets smarter.",
    faq_nao_sabe_responder_q: "What if the chatbot doesn't know how to answer a question?",
    faq_nao_sabe_responder_a: "When the chatbot can't resolve an issue, it automatically transfers to a human agent, ensuring that no customer is left without an answer. You can also configure specific times for this transfer.",
    faq_personalizar_q: "Can I customize the chatbot's responses?",
    faq_personalizar_a: "Yes! You have complete control over the responses. You can create custom flows, define the brand's tone of voice, configure specific responses for different situations, and even train the bot with information about your business.",
    faq_cobranca_q: "How does billing work? Are there long contracts?",
    faq_cobranca_a: "We work only with monthly plans, no long-term commitment. You can cancel at any time. Billing is based on the number of messages processed, ensuring you only pay for what you use.",
    faq_seguranca_q: "Is the system secure? How is customer data handled?",
    faq_seguranca_a: "Yes, security is our priority. All data is encrypted and stored on secure servers. We comply with GDPR and other data protection regulations.",
    faq_conhecimento_tecnico_q: "Do I need technical knowledge to use the platform?",
    faq_conhecimento_tecnico_a: "No! Our platform was developed to be intuitive and easy to use. We offer complete training and our support team is always available to help with any questions.",
    faq_aumentar_vendas_q: "How can the chatbot increase my sales?",
    faq_aumentar_vendas_a: "The chatbot qualifies leads 24/7, answers questions instantly, guides customers through the purchase process, offers related products, and never leaves a customer without service, resulting in more conversions and sales.",

    // Footer
    sobre_nos: "About Us",
    recursos_footer: "Features",
    suporte: "Support",
    todos_direitos: "All rights reserved.",
    revolucione_atendimento_footer: "Revolutionize your customer service with our intelligent chatbot platform. Automation, efficiency, and customer experience in one place.",
    produto: "Product",
    empresa: "Company",
    legal: "Legal",
    sobre: "About",
    blog: "Blog",
    carreiras: "Careers",
    imprensa: "Press",
    central_ajuda: "Help Center",
    documentacao: "Documentation",
    status: "Status",
    contato: "Contact",
    privacidade: "Privacy",
    termos: "Terms",
    lgpd: "GDPR",
    cookies: "Cookies",
    fique_novidades: "Stay up to date with the latest news",
    receba_dicas: "Receive tips, updates, and success stories directly in your email.",
    seu_email: "Your best email",
    inscrever: "Subscribe",
    inscricao_sucesso: "Subscription completed successfully!",
    inscricao_erro: "Error when subscribing",
  }
};

translations.pt = {...globals, ...translations.pt}
translations.en = {...globals, ...translations.en}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('pt');
  const languages: Language[] = ['pt', 'en']

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, languages, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
